[project]
name = "topics-in-djangorestframework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=43.0.3",
    "jwcrypto>=1.5.6",
    "jwt>=1.3.1",
    "pyjwt[crypto]>=2.10.0",
    "requests>=2.32.3",
]
